name: Build
on:
  push:
    branches: [ tp-test ]
jobs:
  image:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: docker build -t hub.pingcap.net/test-store/tp-test .
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: hub.pingcap.net
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    - name: Push
      run: docker push hub.pingcap.net/test-store/tp-test
